[build-system]
requires = ["setuptools>=40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80

[tool.coverage.run]
parallel = true
branch = true
source = ["s1"]

[tool.coverage.report]
show_missing = true
